import type { NextPage } from 'next'
import Head from 'next/head'
import {createTheme, CssBaseline, Grid, ThemeProvider} from "@mui/material";
import Sidebar from '../components/Sidebar';
import "@fontsource/open-sans/400.css"
import "@fontsource/open-sans/500.css"
import {UserInfo} from '../consts/constants';
import Content from "../components/Content";

const theme = createTheme({
   typography: {
       fontSize: 12,
       fontFamily: [
           'Open Sans',
           '-apple-system',
           'BlinkMacSystemFont',
           '"Segoe UI"',
           '"Helvetica Neue"',
           'Arial',
           'sans-serif',
           '"Apple Color Emoji"',
           '"Segoe UI Emoji"',
           '"Segoe UI Symbol"',
       ].join(','),
       h6: {
           fontSize: 16,
       }
   },
});

const Home: NextPage = () => {
    return (
        <ThemeProvider theme={theme}>
            <CssBaseline />
                <Head>
                    <title>Resume - {UserInfo.firstName} {UserInfo.lastName}</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>

                {/*<Header />*/}
                <Grid container component="main" sx={{ height: '100vh' }}>
                    <Sidebar />
                    <Content />
                </Grid>

        </ThemeProvider>
    )
}

export default Home
